# Generated by Django 6.0.1 on 2026-02-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client_requests/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
